### ISSUE TITLE
I can't get the sub mod to work. It keeps saying that there was an exception in the script.

### ISSUE THREAD

**Issue by IndigoSt0rm** [DarkDawnzenith/dark-room#3]
![Screenshot (5)](https://user-images.githubusercontent.com/91354092/134752073-bf374ada-94bf-4166-ae8d-35304ff2647b.png)

**Comment by DarkDawnzenith** [comment]
From what I'm seeing. You're using an unstable version of the mod, in other words, a test build. And also I'm seeing the time system has changed, which is now mas_isDayNow making the blackout code throw that exception.

**Comment by IndigoSt0rm** [comment]
I don't recall changing the time, but the test build I kind of did on accident and now I don't now how to change it back. How would I go about fixing the deprecation issue?

**Comment by DarkDawnzenith** [comment]
I'll go ahead and upload the update. Closing now.
